### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by OMGZui** [fe3dback/str#24]
- 已经有成熟的库了，哥们为何又造了个轮子，是出于怎样的目的呢
- 在造轮子的过程中遇到了怎样的问题
- 这样做与去看源码理解运用的收获差别，毕竟自己再去实现一个需要花很多时间

在此谢谢哥了！

**Comment by irhen** [comment]
It's not really 'another wheel'. Our library is focused on speed. We have tried our best to make it even more useful than before! See the benchmarks to find out more.
PRs are welcome though, if you feel you could help improving it.
Thank you!
